/* drills/0_4.js — Lesson 0.4 · Reading a traceback. Loaded by lib/lesson-reader.js. */
window.LESSON_DRILL_DATA = [
{ name:"bottom-up", title:"Read it upside down",
  concept:"A traceback prints <b>oldest call first, newest last</b>. Your failure is the bottom line. The frames above it are the path that got there — what broke, then where, then how.",
  d1:{ kind:"Fill the blank", ask:"Complete the reading order for any traceback.",
    code:"1. the {{1}} line  → what broke\n2. the frame {{2}} it  → where it broke\n3. the frames {{3}} that → how it got there",
    blanks:[{a:"last",lures:["first","middle"]},{a:"above",lures:["below","beside"]},{a:"above",lures:["below"]}],
    why:"Starting at the top lands you in library code you did not write and cannot fix. Start at the bottom and walk up only as far as your own files." },
  d2:{ kind:"Spot the bug", ask:"Three frames, and the division fails on line 9. Which line holds the bug worth fixing?",
    code:"Traceback (most recent call last):\n  File \"report.py\", line 18, in <module>\n    summary = average(readings)\n  File \"report.py\", line 9, in average\n    return sum(values) / len(values)\nZeroDivisionError: division by zero",
    options:["Line 9 — guard it with <code>if not values: return 0</code> and the error goes away.","Line 18 — <code>readings</code> was already empty when it was passed in, and that is the real fault.","Neither; <code>ZeroDivisionError</code> means the data file is corrupt."],
    answer:1,
    why:"Line 9 is where it <i>surfaced</i>; line 18 is where it <i>started</i>. A guard on line 9 hides an empty dataset — a file that did not load, a filter that matched nothing. The middle frames exist to connect the two." } },

{ name:"type: detail", title:"The last line has two halves",
  concept:"Everything before the colon is the <b>error type</b>, from a short list you will learn by heart. Everything after it is the <b>detail</b> — usually the exact name, key or path that caused the trouble.",
  d1:{ kind:"Fill the blank", ask:"Label the two halves of this last line.",
    code:"NameError: name 'heigth' is not defined\n└─ the {{1}}    └─ the {{2}}",
    blanks:[{a:"type",lures:["frame","file"]},{a:"detail",lures:["traceback","line"]}],
    why:"Two facts and the bug is solved: the category (a name Python could not find) and the name itself (<code>heigth</code>, misspelled)." },
  d2:{ kind:"Spot the bug", ask:"You spend ten minutes re-reading your code after this message. What did it already tell you?",
    code:"KeyError: 'custmer_id'",
    options:["Only that a key is missing — you have to find which one yourself.","The exact misspelled key: the detail names <code>'custmer_id'</code>, so the dictionary has <code>customer_id</code>.","That the dictionary is empty."],
    answer:1,
    why:"The detail after the colon is the answer, not a hint. Same for <code>FileNotFoundError: [Errno 2] ... 'data/logs.txt'</code> — it hands you the exact path it tried. Read it in full before you read your code." } },

{ name:"SyntaxError", title:"The one error whose line number lies",
  concept:"An unclosed bracket means the expression <b>continues onto the next line</b> — which is legal Python. Python reads on and can only complain once it finds something that cannot belong.",
  d1:{ kind:"Fill the blank", ask:"State the rule for SyntaxError line numbers.",
    code:"For SyntaxError, check the line {{1}} the one reported.\nFor every other error type the reported line is {{2}}.",
    blanks:[{a:"above",lures:["below","after"]},{a:"exact",lures:["approximate","off by one"]}],
    why:"The real mistake is at, or just before, the reported line. Everything else — NameError, TypeError, KeyError — points exactly where it failed." },
  d2:{ kind:"Spot the bug", ask:"The missing bracket is on line 4, but Python reports line 5. Why?",
    code:"4   total = sum(a, b\n5   print(total)",
    options:["Python counts from zero, so it is off by one.","Line 4 is still open: Python keeps reading for more arguments and only at <code>print(total)</code> can it tell something is wrong.","The line number is unreliable; ignore it."],
    answer:1,
    why:"Splitting a long expression across lines inside brackets is a deliberate Python feature — so an unclosed <code>(</code> is indistinguishable from a continuation until something illegal shows up." } },

{ name:"moment of use", title:"Python fails when the value is used",
  concept:"C catches type mistakes before the program runs. Python catches them the moment the bad value is actually <b>used</b> — which can be far from where it was created.",
  d1:{ kind:"Fill the blank", ask:"Name the error type each mistake produces.",
    code:"\"3\" + 4        → {{1}}\nwidht          → {{2}}\nif x > 5       → {{3}}",
    blanks:[{a:"TypeError",lures:["ValueError"]},{a:"NameError",lures:["AttributeError"]},{a:"SyntaxError",lures:["IndentationError"]}],
    why:"<code>TypeError</code>: the operation does not fit the types. <code>NameError</code>: no such name. <code>SyntaxError</code>: the missing colon means it is not valid Python at all." },
  d2:{ kind:"Spot the bug", ask:"A wrong value is assigned on line 3 and the traceback points at line 90. Is the traceback wrong?",
    code:"  3   rate = input(\"rate: \")     # a str, not a number\n ...\n 90   total = amount * rate",
    options:["Yes — it should report line 3, where the mistake was written.","No — line 90 is where the str was first used in a way that cannot work; the middle frames are what connect it back to line 3.","Yes — <code>input()</code> should have raised the error immediately."],
    answer:1,
    why:"<code>input()</code> returning a string is perfectly legal; nothing is wrong until something multiplies by it. This is why the call path matters more in Python than the single failing line." } }
];
