/* practice-shelf.js — one source for the "Practice logs" shelf (Phase 4).
 *
 * Reads practice/data/index.js (window.PRACTICE_SET_INDEX, generated by
 * practice_import/nb_to_import_sql.py --json) plus the on-device progress the
 * problem-card page writes (localStorage "commonplace_practice_set_<set>_*").
 * Both the home shelf card (learn-shelf.js) and shelf.html?s=nb-practice
 * (shelf-page.js) ask this file for their numbers, so the counts can't drift.
 *
 * Load after practice/data/index.js:
 *   <script src="practice/data/index.js"></script>
 *   <script src="js/practice-shelf.js"></script>
 */
window.PRACTICE_SHELF = (function () {
  "use strict";

  var LEVELS = ["Beginner", "Intermediate", "Module drills", "Projects", "Templates"];
  var LEVEL_NOTE = {
    "Beginner": "first logs — small problems, many attempts",
    "Intermediate": "longer problems and the structured log format",
    "Module drills": "one module at a time",
    "Projects": "bigger builds and course projects",
    "Templates": "the layout new logs follow"
  };
  var ICON = { "Beginner": "●", "Intermediate": "◐", "Module drills": "✦", "Projects": "▣", "Templates": "★" };
  // Friendlier names than the notebook titles; anything not listed keeps its own title.
  var NAMES = {
    self_practice_beginner: "Beginner",
    self_practice_beginner_from_aistudy: "Beginner (from AI study)",
    self_practice_intermediate: "Intermediate",
    self_practice_intermediate_structured: "Intermediate (structured)",
    random_module_practice: "Random Module",
    random_module_practice_2: "Random Module 2"
  };
  // Pages that are not problem sets (yet): shown on the shelf as plain links.
  var EXTRA = [
    { level: "Projects", icon: "100", title: "100 Days (Angela Yu)", sub: "attempt chains — every try, diffed", href: "100_days/index.html", kind: "project", tag: "signed in" },
    { level: "Projects", icon: "§", title: "Section 3–14", sub: "concept integration exercise — notebook", href: "practice/section_3_14.html", kind: "notebook" },
    { level: "Templates", icon: "★", title: "Golden Problem Template", sub: "problem → attempt → fix → verify", href: "practice/golden_problem_template.html", kind: "notebook" }
  ];

  function ls(k) { try { return JSON.parse(localStorage.getItem(k) || "{}"); } catch (e) { return {}; } }

  // Same rules as lib/practice-set.js: your own mark wins, else the notebook's.
  function progress(st) {
    var P = "commonplace_practice_set_" + st.set;
    var solvedMap = ls(P + "_solved"), att = ls(P + "_attempts");
    var solved = 0, failing = 0;
    (st.problems || []).forEach(function (p) {
      var s = solvedMap[p.id];
      if (s === true || (s !== false && p.nbSolved)) { solved++; return; }
      var a = att[p.id], last = a && a.length ? a[a.length - 1] : null;
      if ((last && last.ok === false) || (!last && s === false)) failing++;
    });
    return { problems: (st.problems || []).length, solved: solved, failing: failing };
  }

  function items() {
    var out = (window.PRACTICE_SET_INDEX || []).map(function (st) {
      var pr = progress(st);
      return { level: st.level || "Projects", icon: ICON[st.level] || "●", title: NAMES[st.set] || st.title,
        href: "practice/set.html?s=" + encodeURIComponent(st.set), nb: "practice/" + st.page, kind: "set",
        problems: pr.problems, solved: pr.solved, failing: pr.failing };
    });
    return out.concat(EXTRA.map(function (x) { var o = {}; for (var k in x) o[k] = x[k]; return o; }));
  }

  function groups() {
    var all = items(), out = [];
    LEVELS.concat(all.map(function (i) { return i.level; })).forEach(function (lv) {
      if (out.some(function (g) { return g.level === lv; })) return;
      var its = all.filter(function (i) { return i.level === lv; });
      if (its.length) out.push({ level: lv, note: LEVEL_NOTE[lv] || "", items: its });
    });
    return out;
  }

  function totals() {
    var t = { logs: 0, sets: 0, problems: 0, solved: 0, failing: 0 };
    items().forEach(function (i) {
      if (i.kind === "project") return;
      t.logs++;
      if (i.kind === "set") { t.sets++; t.problems += i.problems; t.solved += i.solved; t.failing += i.failing; }
    });
    return t;
  }

  var CSS = ''
    + '.psh-group{margin-top:30px}'
    + '.psh-head{display:flex;align-items:baseline;gap:12px;margin:0 0 12px}'
    + '.psh-head h2{font-family:var(--disp,"Cormorant Garamond",serif);font-weight:600;font-size:25px;line-height:1;margin:0;letter-spacing:-.2px}'
    + '.psh-head .note{font-style:italic;font-size:14.5px;color:var(--ink-soft)}'
    + '.psh-head .ln{flex:1;height:1px;background:var(--line);transform:translateY(-5px);min-width:20px}'
    + '.psh-head .c{font-family:var(--mono,"JetBrains Mono",monospace);font-size:10.5px;color:var(--ink-soft);white-space:nowrap}'
    + '.psh-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:12px}'
    + '.psh-card{position:relative;display:flex;flex-direction:column;background:var(--card);border:1px solid var(--line);border-left:3px solid var(--sage);border-radius:10px;transition:transform .14s,box-shadow .14s,border-color .14s}'
    + '.psh-card:hover{transform:translateY(-2px);border-left-color:var(--green);box-shadow:0 12px 26px -18px rgba(20,40,30,.6)}'
    + '.psh-card.project{border-left-color:var(--brass);background:linear-gradient(135deg,var(--card),#f6f1e4)}'
    + '.psh-main{display:flex;gap:12px;align-items:flex-start;padding:14px 16px 12px;text-decoration:none;color:var(--ink);flex:1}'
    + '.psh-main:hover{color:var(--ink)}.psh-main>span:last-child{flex:1;min-width:0}'
    + '.psh-idx{flex:none;font-family:var(--mono,"JetBrains Mono",monospace);font-size:11px;font-weight:700;color:var(--green-dk);background:var(--paper-2);border:1px solid var(--line);border-radius:6px;padding:5px 7px;min-width:34px;text-align:center}'
    + '.psh-t{display:block;font-family:var(--disp,"Cormorant Garamond",serif);font-weight:600;font-size:20px;line-height:1.1}'
    + '.psh-m{display:block;font-family:var(--mono,"JetBrains Mono",monospace);font-size:11px;color:var(--ink-soft);margin-top:5px}'
    + '.psh-m b{color:var(--green-dk)}.psh-m .bad{color:#9a3a2f}'
    + '.psh-sub{display:block;font-style:italic;font-size:14px;color:var(--ink-soft);margin-top:4px}'
    + '.psh-bar{display:block;height:3px;background:var(--line-soft);border-radius:2px;overflow:hidden;margin-top:9px}'
    + '.psh-bar i{display:block;height:100%;background:var(--green)}'
    + '.psh-foot{display:flex;align-items:center;gap:10px;flex-wrap:wrap;padding:0 16px 14px 16px;font-family:var(--mono,"JetBrains Mono",monospace);font-size:11px}'
    + '.psh-foot .go{display:inline-flex;align-items:center;gap:6px;font-weight:700;font-size:11.5px;color:#eef6ef;background:var(--green);border:1px solid var(--green-dk);border-radius:8px;padding:8px 13px;text-decoration:none;min-height:36px;white-space:nowrap}'
    + '.psh-foot .go:hover{background:var(--green-dk);color:#fff}'
    + '.psh-foot .go.quiet{background:var(--card);color:var(--green-dk);border-color:var(--line)}'
    + '.psh-foot .go.quiet:hover{border-color:var(--green)}'
    + '.psh-foot a{color:var(--ink-soft);text-decoration:underline;text-underline-offset:2px}'
    + '.psh-foot a:hover{color:var(--green-dk)}'
    + '.psh-tag{font-weight:700;letter-spacing:1px;text-transform:uppercase;font-size:9.5px;color:#6d5524;background:#efe5cc;border-radius:5px;padding:2px 7px}'
    + '@media (max-width:720px){.psh-head{flex-wrap:wrap;row-gap:2px}.psh-head .ln{display:none}}';
  function injectCss() {
    if (document.getElementById("psh-css")) return;
    var s = document.createElement("style"); s.id = "psh-css"; s.textContent = CSS; document.head.appendChild(s);
  }
  function esc(s) { return String(s == null ? "" : s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }

  function card(i, base) {
    base = base || "";
    var meta = "", foot = "";
    if (i.kind === "set") {
      var pct = i.problems ? Math.round(i.solved / i.problems * 100) : 0;
      meta = '<span class="psh-m">' + i.problems + ' problem' + (i.problems === 1 ? '' : 's') + ' &middot; <b>' + i.solved + '</b> solved'
        + (i.failing ? ' &middot; <span class="bad">' + i.failing + ' failing</span>' : '') + '</span>'
        + '<span class="psh-bar"><i style="width:' + pct + '%"></i></span>';
      foot = '<a class="go" href="' + esc(base + i.href) + '">&#9638; Open problem cards</a><a href="' + esc(base + i.nb) + '">notebook view</a>';
    } else {
      meta = '<span class="psh-sub">' + esc(i.sub || "") + '</span>';
      foot = i.kind === "project" ? '<a class="go quiet" href="' + esc(base + i.href) + '">Open project &rsaquo;</a>' + (i.tag ? '<span class="psh-tag">' + esc(i.tag) + '</span>' : '')
                                  : '<a class="go quiet" href="' + esc(base + i.href) + '">Open notebook &rsaquo;</a>';
    }
    return '<div class="psh-card' + (i.kind === "project" ? " project" : "") + '">'
      + '<a class="psh-main" href="' + esc(base + i.href) + '"><span class="psh-idx">' + esc(i.icon) + '</span>'
      + '<span><span class="psh-t">' + esc(i.title) + '</span>' + meta + '</span></a>'
      + '<div class="psh-foot">' + foot + '</div></div>';
  }

  function html(base) {
    injectCss();
    return groups().map(function (g) {
      var sets = g.items.filter(function (i) { return i.kind === "set"; });
      var p = 0, s = 0; sets.forEach(function (i) { p += i.problems; s += i.solved; });
      var c = sets.length ? '<b>' + s + '</b> / ' + p + ' solved' : g.items.length + (g.items.length === 1 ? ' page' : ' pages');
      return '<section class="psh-group"><div class="psh-head"><h2>' + esc(g.level) + '</h2>'
        + (g.note ? '<span class="note">' + esc(g.note) + '</span>' : '') + '<span class="ln"></span><span class="c">' + c + '</span></div>'
        + '<div class="psh-grid">' + g.items.map(function (i) { return card(i, base); }).join("") + '</div></section>';
    }).join("");
  }

  return { groups: groups, items: items, totals: totals, html: html, progress: progress };
})();
