/* practice-set.js — practice/set.html?s=<set>: a notebook practice log shown as
 * real problem cards (Phase 3).
 *
 * Data:   practice/data/<set>.js  (window.PRACTICE_SETS[set]) — generated by
 *         practice_import/nb_to_import_sql.py --json
 * Store:  the same localStorage shape as the Practice tab (practice-engine.js),
 *         prefix "commonplace_practice_set_<set>":  _solved  _attempts  _code  _bank
 *         (device-only for now; the hub's Mistake Bank tab reads Supabase, so a
 *         saved mistake shows under this page's "In bank" filter).
 * Check:  problems with "expect" are auto-checked (output must match);
 *         the rest are self-check: "Mark solved" / "Still failing".
 */
(function (root) {
  "use strict";

  /* ------------------------------------------------------------ helpers */
  function esc(s) { return String(s == null ? "" : s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
  function el(tag, cls, html) { var e = document.createElement(tag); if (cls) e.className = cls; if (html != null) e.innerHTML = html; return e; }
  function plural(n, w) { return n + " " + w + (n === 1 ? "" : "s"); }
  function normOut(s) { return String(s == null ? "" : s).replace(/\r/g, "").split("\n").map(function (l) { return l.replace(/\s+$/g, ""); }).join("\n").replace(/\n+$/g, ""); }
  function lastLine(e) { var l = String(e).trim().split("\n"); return l[l.length - 1] || "error"; }
  function cleanTitle(s) {
    return String(s).replace(/[\u{1F000}-\u{1FAFF}\u{2190}-\u{21FF}\u{2300}-\u{27BF}\u{2B00}-\u{2BFF}\u{FE00}-\u{FE0F}\u{20E3}]/gu, "")
      .replace(/\s+/g, " ").trim() || "Untitled";
  }
  function normMd(src) {
    var fence = false;
    return String(src).split("\n").map(function (l) {
      if (/^\s*(```|~~~)/.test(l)) { fence = !fence; return l; }
      if (fence) return l;
      return l.replace(/^(\s{0,3}#{1,6})(?=[^#\s])/, "$1 ");
    }).join("\n");
  }
  function md(src) {
    var s = normMd(src);
    if (root.marked) { try { return root.marked.parse(s); } catch (e) {} }
    return "<p>" + esc(s).replace(/\n\n+/g, "</p><p>").replace(/\n/g, "<br>") + "</p>";
  }
  var ROMAN = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII", "XIII", "XIV", "XV"];

  /* ------------------------------------------------- store (Practice-tab shape) */
  function makeStore(P) {
    function ls(k, d) { try { return JSON.parse(localStorage.getItem(k) || d); } catch (e) { return JSON.parse(d); } }
    function put(k, v) { try { localStorage.setItem(k, JSON.stringify(v)); } catch (e) {} }
    var st = {
      att: ls(P + "_attempts", "{}"), code: ls(P + "_code", "{}"), solved: ls(P + "_solved", "{}"), bank: ls(P + "_bank", "{}"),
      saveCode: function () { put(P + "_code", st.code); },
      saveAtt: function () { put(P + "_attempts", st.att); },
      persist: function () { put(P + "_solved", st.solved); put(P + "_bank", st.bank); },
      log: function (id, q, ok, msg) {
        var arr = st.att[id] || (st.att[id] = []), last = arr[arr.length - 1];
        if (!(last && last.q === q && last.ok === ok)) { arr.push({ q: q, ok: ok, msg: msg, t: Date.now() }); if (arr.length > 25) arr.shift(); st.saveAtt(); }
        return st.att[id][st.att[id].length - 1];
      },
      lastAttempt: function (id) { var a = st.att[id]; return a && a.length ? a[a.length - 1] : null; },
      bankAttempt: function (p, a, sec) {
        a.saved = true; st.saveAtt();
        var key = p.id + ":" + a.t;
        st.bank[key] = { key: key, exId: p.id, sec: sec, title: p.title, reason: cap(a.msg || "still failing"), resolved: false, t: a.t };
        st.persist();
      }
    };
    return st;
  }
  function cap(s) { s = String(s || ""); return s.charAt(0).toUpperCase() + s.slice(1); }

  /* ------------------------------------------------------------- Pyodide */
  var py = null, pyReady = false, pyLoading = null, setLed = function () {};
  function ensurePy() {
    if (pyReady) return Promise.resolve(py);
    if (pyLoading) return pyLoading;
    if (typeof root.loadPyodide !== "function") { setLed("Python unavailable", "err"); return Promise.reject(new Error("Python could not load on this page.")); }
    setLed("loading Python…", "loading");
    pyLoading = root.loadPyodide().then(function (p) {
      py = p;
      py.globals.set("__js_input", function (q) { var r = root.prompt(q || ""); return r === null ? "" : r; });
      return py.runPythonAsync(
        "import builtins\n" +
        "__feed = []\n" +
        "__feeding = [False]\n" +
        "def __input(prompt=''):\n" +
        "    if __feeding[0]:\n" +
        "        return str(__feed.pop(0)) if __feed else ''\n" +
        "    r = __js_input(str(prompt))\n" +
        "    print(str(prompt) + str(r))\n" +
        "    return str(r)\n" +
        "builtins.input = __input\n");
    }).then(function () { pyReady = true; setLed("Python ready", "ready"); return py; },
            function (e) { pyLoading = null; setLed("Python failed (offline?)", "err"); throw e; });
    return pyLoading;
  }
  // Each run gets a fresh namespace, so one problem's variables never leak into the next.
  function runPy(code, feed) {
    return ensurePy().then(function (p) {
      var lines = [];
      p.setStdout({ batched: function (s) { lines.push(s); } });
      p.setStderr({ batched: function (s) { lines.push(s); } });
      p.runPython("__feed.clear()");
      if (feed) { p.runPython("__feed.extend(" + JSON.stringify(feed.map(String)) + ")"); }
      p.runPython("__feeding[0] = " + (feed ? "True" : "False"));
      var g = p.globals.get("dict")();
      return p.loadPackagesFromImports(code).catch(function () {}).then(function () {
        return p.runPythonAsync(code, { globals: g });
      }).then(function () { return { out: lines.join("\n"), err: null }; },
              function (e) { return { out: lines.join("\n"), err: String(e && e.message || e) }; })
        .then(function (r) { try { g.destroy(); } catch (e) {} p.runPython("__feeding[0] = False"); return r; });
    });
  }

  /* --------------------------------------------------------------- page */
  function boot() {
    var SET = (new URLSearchParams(location.search).get("s") || "").trim();
    if (!/^[\w.-]+$/.test(SET)) return fail("No problem set chosen. Open this page from the Python hub (Practice logs).");
    var have = root.PRACTICE_SETS && root.PRACTICE_SETS[SET];
    if (have) return render(SET, have);
    var sc = document.createElement("script");
    sc.src = "data/" + SET + ".js";
    sc.onload = function () { var d = root.PRACTICE_SETS && root.PRACTICE_SETS[SET]; d ? render(SET, d) : fail("The data file for “" + SET + "” is empty."); };
    sc.onerror = function () { fail("No data for “" + SET + "” yet. Run <code>practice_import\\nb_to_import_sql.py ../practice/*.html --json</code> to generate it."); };
    document.head.appendChild(sc);
  }
  function fail(msg) {
    document.body.insertAdjacentHTML("afterbegin",
      '<div class="np-layout ps-solo"><main class="np-main"><div class="np-note" style="margin-top:40px">' + msg +
      ' <a href="../index.html">&#8592; Python hub</a></div></main></div>');
  }

  function render(SET, D) {
    var P = "commonplace_practice_set_" + SET;
    var store = makeStore(P);
    var PROBS = D.problems || [];
    document.title = D.title + " · Problems · Python · Commonplace";

    /* sections, in notebook order */
    var sections = [], secIx = {};
    PROBS.forEach(function (p, i) {
      p._n = i + 1;
      var s = p.section || "Problems";
      if (secIx[s] === undefined) { secIx[s] = sections.length; sections.push({ title: s, probs: [] }); }
      sections[secIx[s]].probs.push(p);
    });

    function nbSolved(p) { return (p.attempts || []).some(function (a) { return a.status === "passed"; }); }
    function nbFailedLast(p) { var a = p.attempts || []; return a.length && a[a.length - 1].status === "failed"; }
    function state(p) {
      var s = store.solved[p.id];
      var solved = s === true || (s !== false && nbSolved(p));
      if (solved) return "solved";
      var last = store.lastAttempt(p.id);
      if (last ? last.ok === false : (s === false || nbFailedLast(p))) return "failed";
      return "open";
    }
    function counts() {
      var c = { all: PROBS.length, open: 0, failed: 0, solved: 0 };
      PROBS.forEach(function (p) { var s = state(p); c[s]++; });
      c.unsolved = c.open + c.failed;
      c.banked = PROBS.filter(banked).length;
      return c;
    }

    /* ---- shell (shares the notebook player's classes) ---- */
    var body = document.body;
    var bar = el("header", "np-bar");
    bar.innerHTML =
      '<div class="np-bar-in">' +
        '<a class="np-hbtn home" href="../../../index.html" title="Commonplace home">&#8962;<span class="lbl-long"> Home</span></a>' +
        '<a class="np-hbtn" href="../index.html" title="Python hub">&#8249; Python</a>' +
        '<span class="np-ttl">~/python/practice/<b>' + esc(SET) + '</b> · problems</span>' +
        '<span class="np-led" id="np-led" role="status" aria-live="polite"><span class="dot"></span><span class="t" id="np-led-t">Python not loaded</span></span>' +
        '<span class="np-prog" title="problems solved"><span class="track"><span class="fill" id="np-fill"></span></span><span class="pc" id="np-pc"></span></span>' +
      '</div>';
    var jump = el("div", "np-jump");
    jump.innerHTML = '<select id="np-sel" aria-label="Jump to problem"></select><span class="np-pos" id="np-pos-m"></span>';
    var layout = el("div", "np-layout");
    var rail = el("aside", "np-rail"); rail.setAttribute("aria-label", "Problems");
    rail.innerHTML = '<div class="np-rail-in"><div class="np-rail-k">Problems</div><div class="np-pos" id="np-pos-d"></div><ul class="np-ol" id="np-ol"></ul></div>';
    var main = el("main", "np-main");
    main.innerHTML =
      '<nav class="np-crumb" aria-label="Breadcrumb"><a href="../../../index.html">Commonplace</a><span class="sep">/</span>' +
        '<a href="../../index.html">Coding</a><span class="sep">/</span><a href="../index.html">Python</a><span class="sep">/</span>' +
        '<span class="here">' + esc(D.title) + '</span></nav>' +
      '<header class="np-mast" data-file="' + esc(D.page || "") + '">' +
        '<span class="np-wdots"><i class="r"></i><i class="y"></i><i class="g"></i></span>' +
        '<div class="k">Practice &#183; ' + esc(D.level || "Problem set") + '</div>' +
        '<h1>' + esc(D.title) + '</h1>' +
        '<p class="sub">Every problem from the notebook as its own card: read it, look back at your earlier attempts, then solve it again. ' +
          'Problems without an expected output are self-checked &#8212; run it, then mark it solved or still failing.</p>' +
        '<div class="meta" id="ps-meta"></div>' +
        '<div class="acts">' + (D.page ? '<a class="np-btn" href="' + esc(D.page) + '">&#9636; View as notebook</a>' : '') + '</div>' +
      '</header>' +
      '<div class="ps-filters" role="toolbar" aria-label="Filter problems" id="ps-filters"></div>' +
      '<div id="ps-list"></div>' +
      '<div class="np-note">Solved state, attempts and saved mistakes are kept on this device. <b>Save to bank</b> adds the problem to the ' +
        '<b>In bank</b> filter above. <code>Shift+Enter</code> runs, <code>Ctrl+Enter</code> checks.</div>' +
      '<footer class="np-colophon"><span><a href="../index.html">&#8592; Python hub</a></span><span>' + esc(PROBS.length + " problems from " + (D.page || SET)) + '</span></footer>';
    layout.appendChild(rail); layout.appendChild(main);
    body.insertBefore(layout, body.firstChild);
    body.insertBefore(jump, layout);
    body.insertBefore(bar, jump);
    var led = document.getElementById("np-led"), ledT = document.getElementById("np-led-t");
    setLed = function (t, c) { led.className = "np-led " + (c || ""); ledT.textContent = t; };

    /* ---- filter row ---- */
    var FILTERS = [["all", "All"], ["unsolved", "Unsolved"], ["failed", "Failed"], ["solved", "Solved"], ["banked", "In bank"]];
    function banked(p) { for (var k in store.bank) if (store.bank[k].exId === p.id && !store.bank[k].resolved) return true; return false; }
    var filter = "all";
    try { filter = localStorage.getItem(P + "_filter") || "all"; } catch (e) {}
    var fbox = document.getElementById("ps-filters");
    function paintFilters() {
      var c = counts();
      fbox.innerHTML = FILTERS.map(function (f) {
        var n = f[0] === "all" ? c.all : c[f[0]];
        return '<button type="button" class="ps-chip' + (filter === f[0] ? " on" : "") + '" data-f="' + f[0] + '" aria-pressed="' + (filter === f[0]) + '">' +
          f[1] + ' <span class="n">' + n + '</span></button>';
      }).join("");
      document.getElementById("ps-meta").innerHTML =
        '<span>' + plural(c.all, "problem") + '</span><span>&#183;</span><span><b>' + c.solved + '</b> solved</span><span>&#183;</span>' +
        '<span>' + c.failed + ' failing</span><span>&#183;</span><span>' + plural(sections.length, "section") + '</span>';
      document.getElementById("np-fill").style.width = (c.all ? Math.round(c.solved / c.all * 100) : 0) + "%";
      document.getElementById("np-pc").textContent = c.solved + " / " + c.all + " solved";
    }
    fbox.addEventListener("click", function (e) {
      var b = e.target.closest(".ps-chip"); if (!b) return;
      filter = b.getAttribute("data-f");
      try { localStorage.setItem(P + "_filter", filter); } catch (e2) {}
      applyFilter();
    });

    /* ---- cards ---- */
    var list = document.getElementById("ps-list");
    var cards = {}, railLinks = {}, secEls = [];
    sections.forEach(function (sec, si) {
      var sh = el("div", "ps-sec");
      sh.innerHTML = '<span class="n">&#167; ' + (ROMAN[si] || si + 1) + '</span><h2>' + esc(cleanTitle(sec.title)) + '</h2><span class="c">' + plural(sec.probs.length, "problem") + '</span><span class="ln"></span>';
      list.appendChild(sh);
      secEls.push({ el: sh, sec: sec });
      sec.probs.forEach(function (p) { var c = buildCard(p, sec); cards[p.id] = c; list.appendChild(c.el); });
    });

    function badge(s) {
      return s === "solved" ? '<span class="ps-st solved">&#10003; Solved</span>' :
             s === "failed" ? '<span class="ps-st failed">&#10005; Failing</span>' : '<span class="ps-st open">Unsolved</span>';
    }

    function buildCard(p, sec) {
      var card = el("article", "ps-card");
      card.id = "p-" + p.id;
      var hasExpect = p.expect != null;
      var atts = p.attempts || [];
      var nPass = atts.filter(function (a) { return a.status === "passed"; }).length;
      var nFail = atts.filter(function (a) { return a.status === "failed"; }).length;

      var head = el("header", "ps-head");
      head.innerHTML = '<span class="ps-num">' + String(p._n).padStart(2, "0") + '</span>' +
        '<h3>' + esc(cleanTitle(p.title)) + '</h3><span class="ps-badge"></span>';
      card.appendChild(head);

      if (p.statement && cleanTitle(p.statement) !== cleanTitle(p.title)) { var st = el("div", "np-md ps-statement", md(p.statement)); card.appendChild(st); }
      (p.examples || []).forEach(function (ex, i) {
        var e = el("div", "ps-ex");
        e.innerHTML = '<div class="k">Example' + ((p.examples.length > 1) ? " " + (i + 1) : "") + '</div><pre>' + esc(ex) + '</pre>';
        card.appendChild(e);
      });

      if (atts.length) {
        var det = el("details", "ps-att");
        var sum = [];
        if (nFail) sum.push(nFail + " failed"); if (nPass) sum.push(nPass + " passed");
        if (atts.length - nFail - nPass) sum.push((atts.length - nFail - nPass) + " unmarked");
        det.innerHTML = '<summary>Your notebook attempts &#183; ' + atts.length + ' <span class="sub">(' + sum.join(", ") + ')</span></summary>';
        atts.forEach(function (a, i) {
          var row = el("div", "ps-att-row");
          var lab = a.status === "passed" ? "passed" : a.status === "failed" ? "failed" : "unmarked";
          row.innerHTML = '<div class="ps-att-top"><span class="ps-tag ' + lab + '">' + lab + '</span>' +
            '<span class="ps-att-m">Attempt ' + (i + 1) + (a.marker ? " &#183; " + esc(cleanTitle(a.marker)) : "") + '</span></div>' +
            '<pre class="ps-code">' + esc(a.code.replace(/^\n+|\s+$/g, "")) + '</pre>';
          var load = el("button", "np-mini ps-load", "Load into editor"); load.type = "button";
          load.onclick = function () { ed.set(a.code.replace(/^\n+|\s+$/g, "")); ed.focus(); };
          row.querySelector(".ps-att-top").appendChild(load);
          det.appendChild(row);
        });
        card.appendChild(det);
      }

      /* editor */
      var cell = el("div", "np-cell ps-editor");
      var top = el("div", "top");
      top.innerHTML = '<span class="pip"></span><span class="lbl">solution.py</span>';
      var reset = el("button", "np-mini", "Clear"); reset.type = "button"; reset.title = "Empty the editor";
      top.appendChild(reset);
      var ta = el("textarea", "np-ta"); ta.spellcheck = false;
      ta.value = store.code[p.id] != null ? store.code[p.id] : "";
      ta.placeholder = "# Solve it again here — or load one of your attempts above";
      ta.rows = Math.max(4, Math.min(20, ta.value.split("\n").length + 1));
      var out = el("pre", "np-out"); out.setAttribute("data-ix", p._n); out.setAttribute("aria-live", "polite");
      cell.appendChild(top); cell.appendChild(ta); cell.appendChild(out);
      card.appendChild(cell);

      var acts = el("div", "ps-acts");
      var runB = el("button", "np-run", "&#9654; Run"); runB.type = "button"; runB.title = "Run (Shift+Enter)";
      acts.appendChild(runB);
      var checkB, solvedB, failB;
      if (hasExpect) { checkB = el("button", "np-btn go", "&#10003; Check"); checkB.type = "button"; checkB.title = "Compare your output with the expected output (Ctrl+Enter)"; acts.appendChild(checkB); }
      else {
        solvedB = el("button", "np-btn go", "&#10003; Mark solved"); solvedB.type = "button";
        failB = el("button", "np-btn", "&#10005; Still failing"); failB.type = "button";
        acts.appendChild(solvedB); acts.appendChild(failB);
      }
      var bankB = el("button", "np-btn ps-bank", "&#9873; Save to bank"); bankB.type = "button";
      bankB.title = "Keep this miss in the bank to drill later";
      acts.appendChild(bankB);
      var fb = el("div", "ps-fb"); fb.setAttribute("role", "status");
      card.appendChild(acts); card.appendChild(fb);

      /* editor wiring: CodeMirror once the card is near the screen */
      var cm = null;
      var ed = {
        get: function () { return cm ? cm.getValue() : ta.value; },
        set: function (v) { if (cm) cm.setValue(v); else { ta.value = v; save(); } },
        focus: function () { if (cm) cm.focus(); else ta.focus(); }
      };
      function save() { store.code[p.id] = ed.get(); store.saveCode(); }
      ed.upgrade = function () {
        if (cm || !root.CodeMirror) return;
        cm = root.CodeMirror.fromTextArea(ta, { mode: "python", lineNumbers: true, indentUnit: 4, viewportMargin: Infinity,
          extraKeys: { "Shift-Enter": doRun, "Ctrl-Enter": hasExpect ? doCheck : doRun, "Cmd-Enter": hasExpect ? doCheck : doRun,
            "Tab": function (c) { c.execCommand(c.somethingSelected() ? "indentMore" : "insertSoftTab"); } } });
        cm.on("change", save);
      };
      ta.addEventListener("input", save);
      ta.addEventListener("keydown", function (e) {
        if (e.key === "Enter" && e.shiftKey) { e.preventDefault(); doRun(); }
        else if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) { e.preventDefault(); hasExpect ? doCheck() : doRun(); }
      });
      reset.onclick = function () { ed.set(""); out.className = "np-out"; out.textContent = ""; showFb(null); };

      function showOut(text, isErr) { out.className = "np-out show" + (isErr ? " err" : ""); out.textContent = text || "(ran — no output)"; }
      function showFb(kind, msg) { fb.className = "ps-fb" + (kind ? " " + kind : ""); fb.textContent = msg || ""; }
      function busy(on) { runB.disabled = on; if (checkB) checkB.disabled = on; }

      function doRun() {
        var code = ed.get();
        if (!code.trim()) { showFb("bad", "Write or load some code first."); return; }
        busy(true); showFb(null); showOut("running…");
        runPy(code, null).then(function (r) {
          showOut(r.err ? (r.out ? r.out + "\n" : "") + r.err : r.out, !!r.err);
          if (r.err) showFb("bad", "✕ " + lastLine(r.err));
          else if (!hasExpect) showFb("info", "Ran without errors. Does it do what the problem asks? Mark it solved or still failing.");
        }).catch(function (e) { showOut(String(e.message || e), true); })
          .then(function () { busy(false); });
      }
      function doCheck() {
        var code = ed.get();
        if (!code.trim()) { showFb("bad", "Write or load some code first."); return; }
        busy(true); showFb(null); showOut("checking…");
        runPy(code, p.stdin || []).then(function (r) {
          if (r.err) { var s = lastLine(r.err); showOut((r.out ? r.out + "\n" : "") + r.err, true); store.log(p.id, code, false, s); showFb("bad", "✕ " + s); }
          else {
            var ok = normOut(r.out) === normOut(p.expect);
            showOut(r.out, false);
            store.log(p.id, code, ok, ok ? "" : "wrong output");
            if (ok) { store.solved[p.id] = true; store.persist(); showFb("ok", "✓ Correct — output matches the expected result."); }
            else showFb("bad", "✕ Output doesn't match the expected result yet.");
          }
          refresh();
        }).catch(function (e) { showOut(String(e.message || e), true); })
          .then(function () { busy(false); });
      }
      runB.onclick = doRun;
      if (checkB) checkB.onclick = doCheck;
      if (solvedB) solvedB.onclick = function () {
        store.log(p.id, ed.get(), true, ""); store.solved[p.id] = true; store.persist();
        showFb("ok", "✓ Marked solved."); refresh();
      };
      if (failB) failB.onclick = function () {
        store.log(p.id, ed.get(), false, "still failing"); store.solved[p.id] = false; store.persist();
        showFb("bad", "Marked as still failing — Save to bank to drill it later."); refresh();
      };
      bankB.onclick = function () {
        var a = store.lastAttempt(p.id);
        if (!a || a.ok !== false) {
          a = store.log(p.id, ed.get(), false, hasExpect ? "wrong output" : "still failing");
          if (store.solved[p.id] !== true) { store.solved[p.id] = false; store.persist(); }
        }
        if (a.saved) { showFb("info", "Already in the bank."); return; }
        store.bankAttempt(p, a, cleanTitle(sec.title));
        showFb("ok", "⚑ Saved to the bank — find it under the In bank filter."); refresh();
      };

      function refresh() {
        var s = state(p);
        card.setAttribute("data-state", s);
        head.querySelector(".ps-badge").outerHTML = '<span class="ps-badge">' + badge(s) + '</span>';
        var a = store.lastAttempt(p.id);
        var banked = a && a.saved;
        bankB.disabled = !!banked; bankB.innerHTML = banked ? "&#9873; In the bank" : "&#9873; Save to bank";
        if (railLinks[p.id]) railLinks[p.id].setAttribute("data-state", s);
        if (refresh.all) refresh.all();
      }
      return { el: card, p: p, ed: ed, refresh: refresh };
    }

    /* ---- outline (rail + phone select) ---- */
    var ol = document.getElementById("np-ol"), sel = document.getElementById("np-sel");
    function buildOutline() {
      ol.innerHTML = ""; sel.innerHTML = "";
      var o0 = el("option"); o0.value = ""; o0.textContent = "Top of page"; sel.appendChild(o0);
      sections.forEach(function (sec, si) {
        var vis = sec.probs.filter(visible);
        if (!vis.length) return;
        ol.appendChild(el("li", "grp", "&#167; " + (ROMAN[si] || si + 1) + " " + esc(cleanTitle(sec.title))));
        var og = document.createElement("optgroup"); og.label = "§ " + (ROMAN[si] || si + 1) + " " + cleanTitle(sec.title); sel.appendChild(og);
        vis.forEach(function (p) {
          var li = el("li"), a = el("a");
          a.href = "#p-" + p.id; a.setAttribute("data-state", state(p));
          a.innerHTML = '<span class="n">' + String(p._n).padStart(2, "0") + '</span><span class="t">' + esc(cleanTitle(p.title)) + '</span>';
          a.onclick = function (e) { e.preventDefault(); go(p.id); };
          li.appendChild(a); ol.appendChild(li); railLinks[p.id] = a;
          var o = el("option"); o.value = p.id; o.textContent = p._n + ". " + cleanTitle(p.title); og.appendChild(o);
        });
      });
    }
    sel.onchange = function () { if (!sel.value) window.scrollTo({ top: 0 }); else go(sel.value); };
    function go(id) { var c = cards[id]; if (!c) return; c.el.scrollIntoView({ block: "start", behavior: "auto" }); c.ed.upgrade(); onScroll(true); }

    function visible(p) {
      var s = state(p);
      if (filter === "banked") return banked(p);
      return filter === "all" || (filter === "unsolved" && s !== "solved") || filter === s;
    }
    function applyFilter() {
      PROBS.forEach(function (p) { cards[p.id].el.hidden = !visible(p); });
      secEls.forEach(function (x) { x.el.hidden = !x.sec.probs.some(visible); });
      var shown = PROBS.filter(visible).length;
      var empty = document.getElementById("ps-empty");
      if (!shown) {
        if (!empty) { empty = el("div", "np-note ps-empty"); empty.id = "ps-empty"; list.appendChild(empty); }
        empty.innerHTML = filter === "banked" ? "Nothing in the bank from this set. Use <b>Save to bank</b> on a problem you keep missing." : filter === "failed" ? "Nothing failing right now." : filter === "solved" ? "Nothing solved yet &#8212; pick a problem and mark it when it works." : "Every problem here is solved. &#10003;";
      } else if (empty) empty.remove();
      paintFilters(); buildOutline(); curP = null; onScroll(true);
    }

    /* ---- scroll tracking: "Problem 7 of 60" ---- */
    var curP = null;
    function onScroll(force) {
      var y = window.innerWidth >= 1100 ? 130 : 190, hit = null;
      for (var i = 0; i < PROBS.length; i++) {
        var c = cards[PROBS[i].id]; if (c.el.hidden) continue;
        if (c.el.getBoundingClientRect().top <= y) hit = PROBS[i]; else break;
      }
      if (!force && hit === curP) return;
      curP = hit;
      Object.keys(railLinks).forEach(function (id) { railLinks[id].classList.toggle("on", hit && id === hit.id); });
      sel.value = hit ? hit.id : "";
      var shownList = PROBS.filter(visible), k = hit ? shownList.indexOf(hit) + 1 : 0;
      document.getElementById("np-pos-d").innerHTML = hit ? "Problem <b>" + hit._n + "</b> of " + PROBS.length :
        plural(shownList.length, "problem") + (filter === "all" ? "" : " shown");
      document.getElementById("np-pos-m").textContent = hit ? k + " / " + shownList.length : "";
      if (hit && railLinks[hit.id]) {
        var box = rail.querySelector(".np-rail-in"), a = railLinks[hit.id], r = a.getBoundingClientRect(), b = box.getBoundingClientRect();
        if (r.top < b.top + 40 || r.bottom > b.bottom - 20) box.scrollTop += (r.top - b.top) - box.clientHeight / 2;
      }
    }
    var ticking = false;
    window.addEventListener("scroll", function () { if (!ticking) { ticking = true; requestAnimationFrame(function () { ticking = false; onScroll(); }); } }, { passive: true });
    window.addEventListener("resize", function () { onScroll(true); });

    /* lazy CodeMirror: only for cards near the screen */
    if ("IntersectionObserver" in root) {
      var io = new IntersectionObserver(function (es) {
        es.forEach(function (e) { if (e.isIntersecting) { var id = e.target.id.slice(2); if (cards[id]) cards[id].ed.upgrade(); io.unobserve(e.target); } });
      }, { rootMargin: "600px 0px" });
      PROBS.forEach(function (p) { io.observe(cards[p.id].el); });
    } else PROBS.forEach(function (p) { cards[p.id].ed.upgrade(); });

    var allRefresh = function () { paintFilters(); };
    PROBS.forEach(function (p) { cards[p.id].refresh.all = null; cards[p.id].refresh(); cards[p.id].refresh.all = allRefresh; });
    applyFilter();
    var want = /^#p-(.+)$/.exec(location.hash || "");
    if (want && cards[want[1]]) setTimeout(function () { go(want[1]); }, 60);
    setTimeout(function () { ensurePy().catch(function () {}); }, 800);
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot); else boot();
})(window);
