-- Generated by nb_to_import_sql.py  (topic-tagged)
-- import tag: import:intermediate-structured   subject: python   problems: 12   attempts: 13
-- options: all-unresolved=true  bank-all=true   section tag = topic bucket
-- Resolves user_id from auth.users by login email. Idempotent for this tag.

BEGIN;

DO $IMPORT$
DECLARE
  uid    uuid;
  ex_id  uuid;
  att_id uuid;
BEGIN
  SELECT id INTO uid FROM auth.users WHERE email = $c$mangaonkaraniket@gmail.com$c$ LIMIT 1;
  IF uid IS NULL THEN
    RAISE EXCEPTION 'No auth user for email %', $c$mangaonkaraniket@gmail.com$c$;
  END IF;

  DELETE FROM commonplace_mistakes m USING commonplace_exercises e
   WHERE m.exercise_id = e.id AND e.user_id = uid
     AND e.subject = $c$python$c$ AND e.tags && ARRAY[$c$import:intermediate-structured$c$]::text[];
  DELETE FROM commonplace_attempts a USING commonplace_exercises e
   WHERE a.exercise_id = e.id AND e.user_id = uid
     AND e.subject = $c$python$c$ AND e.tags && ARRAY[$c$import:intermediate-structured$c$]::text[];
  DELETE FROM commonplace_exercises e
   WHERE e.user_id = uid
     AND e.subject = $c$python$c$ AND e.tags && ARRAY[$c$import:intermediate-structured$c$]::text[];

  -- [0] Section 15: Local Development Environment Setup & the Coffee Machine  ->  Data & Spreadsheets  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Section 15: Local Development Environment Setup & the Coffee Machine$c$, $c$Section 15: Local Development Environment Setup & the Coffee Machine$c$, NULL,
          ARRAY[$c$import:intermediate-structured$c$, $c$topic:Data & Spreadsheets$c$]::text[], 0)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$# Let's generate SFD and BMD for a simply supported beam with a uniform distributed load (UDL).
# Example values:
#   - Beam length L = 6 m
#   - UDL w = 4 kN/m
#
# For a simply supported beam with full-span UDL:
#   Reactions: R1 = R2 = w*L/2
#   Shear:    V(x) = R1 - w*x
#   Moment:   M(x) = R1*x - (w*x**2)/2
#
# We'll:
# 1) Compute V(x) and M(x) over the span
# 2) Plot SFD and BMD as two separate charts (no subplots)
# 3) Save the figures for download

import numpy as np
import matplotlib.pyplot as plt

# Example parameters
L = 6.0       # meters
w = 4.0       # kN/m

# Reactions
R1 = w * L / 2.0
R2 = R1

# Discretize the span
x = np.linspace(0, L, 500)

# SFD and BMD
V = R1 - w * x
M = R1 * x - 0.5 * w * x**2

# Theoretical max moment for a full-span UDL on a simply supported beam
x_Mmax = L / 2.0
M_max = w * L**2 / 8.0

# ----- Plot SFD -----
plt.figure()
plt.plot(x, V, linewidth=2)
plt.axhline(0, linewidth=1)
plt.title(f"Shear Force Diagram (SFD) — UDL w={w} kN/m, L={L} m")
plt.xlabel("x (m)")
plt.ylabel("Shear V(x) [kN]")
plt.grid(True, which="both", linestyle="--", alpha=0.5)
plt.tight_layout()
sfd_path = "SFD_UDL.png"
plt.savefig(sfd_path, dpi=180)
plt.show()

# ----- Plot BMD -----
plt.figure()
plt.plot(x, M, linewidth=2)
plt.axhline(0, linewidth=1)
# mark max moment at midspan
plt.scatter([x_Mmax], [M_max])
plt.title(f"Bending Moment Diagram (BMD) — UDL w={w} kN/m, L={L} m\nM_max = {M_max:.2f} kN·m at x = {x_Mmax:.2f} m")
plt.xlabel("x (m)")
plt.ylabel("Moment M(x) [kN·m]")
plt.grid(True, which="both", linestyle="--", alpha=0.5)
plt.tight_layout()
bmd_path = "BMD_UDL.png"
plt.savefig(bmd_path, dpi=180)
plt.show()

# Prepare a concise summary and file paths for user reference
sfd_path, bmd_path, R1, R2, M_max$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$🧪 Attempt — Raw / Intermediate Thinking (DO NOT EDIT)$c$, false);

  -- [1] 4. Multiple ifs  ->  Conditionals & Logic  (2 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$4. Multiple ifs$c$, $c$4. Multiple ifs$c$, NULL,
          ARRAY[$c$import:intermediate-structured$c$, $c$topic:Conditionals & Logic$c$]::text[], 1)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$print("Welcome to the rollercoaster!")
height = int(input("What is your height in cm? "))
ticket = 0

if height >= 120:
    print("You can ride the rollercoaster")
    age = int(input("What is your age? "))
    if age <= 12:
        ticket = 5
        print("Please pay $5.")
    elif age <= 18:
        ticket = 7
        print("Please pay $7.")
    else:
        ticket = 12
        print("Please pay $12.")

    want_photo = input("Would you like photo? (Y/N) ")
    if want_photo == "Y":
        #print(f"Your updated ticket value is {ticket} + 3") Confused here
        #print(f"Your updated ticket value is {ticket + 3}") Confused here


        print(f"Your updated ticket value is {ticket} + {3}")
    else:
        print(f"Your ticket value is {ticket}")
else:
    print("Sorry you have to grow taller before you can ride.")$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$🧪 Attempt — Raw / Intermediate Thinking (DO NOT EDIT)$c$, false);
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$!apt install graphviz
!pip install graphviz

from graphviz import Digraph

g = Digraph()
g.edge("Start", "Check Name")
g.edge("Check Name", "Say Hello")
g.edge("Say Hello", "End")

g.render('flowchart', format='png', view=True)
g$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$🧪 Attempt — Raw / Intermediate Thinking (DO NOT EDIT)$c$, false);

  -- [2] Section 17: The Quiz Project & the Benefits of OOP  ->  OOP  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Section 17: The Quiz Project & the Benefits of OOP$c$, $c$Section 17: The Quiz Project & the Benefits of OOP$c$, NULL,
          ARRAY[$c$import:intermediate-structured$c$, $c$topic:OOP$c$]::text[], 2)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$question_data = [
{"text": "A slug's blood is green.", "answer": "True"},
{"text": "The loudest animal is the African Elephant.", "answer": "False"},
{"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
{"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
{"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
{"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
{"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
{"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
{"text": "Google was originally called 'Backrub'.", "answer": "True"},
{"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
{"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
{"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$🧪 Attempt — Raw / Intermediate Thinking (DO NOT EDIT)$c$, false);

  -- [3] question_model  ->  OOP  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$question_model$c$, $c$question_model$c$, NULL,
          ARRAY[$c$import:intermediate-structured$c$, $c$topic:OOP$c$]::text[], 3)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$class Question:

    def __init__ (self, q_text, q_answer):
        self.text = q_text
        self.answer = q_answer$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$🧪 Attempt — Raw / Intermediate Thinking (DO NOT EDIT)$c$, false);

  -- [4] Main failed 1  ->  OOP  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Main failed 1$c$, $c$Main failed 1$c$, NULL,
          ARRAY[$c$import:intermediate-structured$c$, $c$topic:OOP$c$]::text[], 4)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$import Question from question_model
import question_data from data

question_bank = []

for i in question_data:
    question_bank[i] = question_data["task"][i]

print(question_bank)$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$🧪 Attempt — Raw / Intermediate Thinking (DO NOT EDIT)$c$, false);

  -- [5] Main failed 2  ->  OOP  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Main failed 2$c$, $c$Main failed 2$c$, NULL,
          ARRAY[$c$import:intermediate-structured$c$, $c$topic:OOP$c$]::text[], 5)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$import Question from question_model
import question_data from data

question_bank = []

for i in question_data:
    question_text = question_data["text"]
    question_answer = question_data["answer"]

    question_bank[i] = question_data["task"]

print(question_bank)$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$🧪 Attempt — Raw / Intermediate Thinking (DO NOT EDIT)$c$, false);

  -- [6] Main failed 3  ->  OOP  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Main failed 3$c$, $c$Main failed 3$c$, NULL,
          ARRAY[$c$import:intermediate-structured$c$, $c$topic:OOP$c$]::text[], 6)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$import Question from question_model
import question_data from data

question_bank = []

for i in question_data:
    question_text = question_data["text"]
    question_answer = question_data["answer"]
    question_bank[i] = question_data["task"]

print(question_bank)$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$🧪 Attempt — Raw / Intermediate Thinking (DO NOT EDIT)$c$, false);

  -- [7] Main failed 4  ->  OOP  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Main failed 4$c$, $c$Main failed 4$c$, NULL,
          ARRAY[$c$import:intermediate-structured$c$, $c$topic:OOP$c$]::text[], 7)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$import Question from question_model
import question_data from data

question_bank = []

for i in question_data:
    question_text = question_data["text"]
    question_answer = question_data["answer"]
    new_question = Question(question_text,question_answer)
    question_bank.append(new_question)

print(question_bank)$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$🧪 Attempt — Raw / Intermediate Thinking (DO NOT EDIT)$c$, false);

  -- [8] quiz_brain  ->  OOP  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$quiz_brain$c$, $c$quiz_brain$c$, NULL,
          ARRAY[$c$import:intermediate-structured$c$, $c$topic:OOP$c$]::text[], 8)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$#from question_model import Question
#from data import question_data

class QuizBrain:

    def __init__(self, q_list):
        self.question_number = 0
        self.question_list = q_list
        self.score = 0

    def still_has_questions(self):
        return self.question_number < len(self.question_list)

    def new_question(self):
        current_question = self.question_list[self.question_number]
        self.question_number += 1
        user_answer = input(f"Q. {self.question_number} {current_question.text} (True/False): ")
        self.check_answer(user_answer, current_question.answer)
        print(f"Your current score is: {self.score}/{self.question_number}")
        print("\n")

    def check_answer(self, user_answer, correct_answer):
        if user_answer.lower() == correct_answer.lower():
            self.score += 1
            print("You got it right!")
        else:
            print("That's wrong.")
        print(f"The correct answer was: {correct_answer}.")$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$🧪 Attempt — Raw / Intermediate Thinking (DO NOT EDIT)$c$, false);

  -- [9] Main  ->  OOP  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Main$c$, $c$Main$c$, NULL,
          ARRAY[$c$import:intermediate-structured$c$, $c$topic:OOP$c$]::text[], 9)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$#from question_model import Question
#from data import question_data
#from quiz_brain import QuizBrain

question_bank = []

for question in question_data:
    question_text = question["text"]
    question_answer = question["answer"]
    new_question = Question(question_text,question_answer)
    question_bank.append(new_question)

print(question_bank)

quiz = QuizBrain(question_bank)

while quiz.still_has_questions:
    quiz.new_question()$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$🧪 Attempt — Raw / Intermediate Thinking (DO NOT EDIT)$c$, false);

  -- [10] Please choose between the following options,  ->  Games & Projects  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Please choose between the following options,$c$, $c$Please choose between the following options,$c$, NULL,
          ARRAY[$c$import:intermediate-structured$c$, $c$topic:Games & Projects$c$]::text[], 10)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$import random

def user_ip():

  print("Please choose between the following options,")
  print("1: Rock")
  print("2: Paper")
  print("3: Scissors")
  print("4: Quit")
  a= int(input("Please enter your Input: "))

  return a

while True:
  a=user_ip()
  b=random.randint(1,3)

  print ("You chose: " + str(a))
  print ("Computer chose: " + str(b))

  if (a==4):
    print ("Game is over!")
    break

  else:
    if ((a==1 and b == 3) or (a==2 and b==1) or (a==3 and b==2)):
      print("You won!!!")

    elif((a==1 and b == 2) or (a==2 and b == 3) or (a==3 and b == 1)):
      print("You lost")

    elif(a==b):
      print("It's a Tie")

    else:
      print("This input is not recognised. Please choose option between 1-3 or 4 to quit the game.")$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$🧪 Attempt — Raw / Intermediate Thinking (DO NOT EDIT)$c$, false);

  -- [11] Me and computer will roll the dices.  ->  Games & Projects  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Me and computer will roll the dices.$c$, $c$Me and computer will roll the dices.$c$, NULL,
          ARRAY[$c$import:intermediate-structured$c$, $c$topic:Games & Projects$c$]::text[], 11)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$import random

def user_input():
  print("Enter y to start the game/n")
  print("Enter q to quit the game")

  a= int(input("Please enter your Input: "))

  return a


while True:

  a= user_input()
  roll_b = 1
  roll_c = 1

  b = random.randint(1,6)
  c = random.randint(1,6)

  if (a == "q"):
    print("Game is over")
    break

  elif (roll_b == 6 and roll_c == 6):
    print("The results are,/n")
    print("The use score is: {b},/n")
    print("The computer score is: {c},/n")

  # Counting the dice rolls for user

  else:
    for roll in range (1,6):
      if (b != 6):
        roll_b += roll_b
      else:
        roll_b

    count_b = b
    b= b+ count_b

    print("User score is: " + str(b))$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$🧪 Attempt — Raw / Intermediate Thinking (DO NOT EDIT)$c$, false);

END
$IMPORT$;

COMMIT;
