-- Generated by nb_to_import_sql.py  (topic-tagged)
-- import tag: import:random-module   subject: python   problems: 10   attempts: 12
-- options: all-unresolved=true  bank-all=true   section tag = topic bucket
-- Resolves user_id from auth.users by login email. Idempotent for this tag.

BEGIN;

DO $IMPORT$
DECLARE
  uid    uuid;
  ex_id  uuid;
  att_id uuid;
BEGIN
  SELECT id INTO uid FROM auth.users WHERE email = $c$mangaonkaraniket@gmail.com$c$ LIMIT 1;
  IF uid IS NULL THEN
    RAISE EXCEPTION 'No auth user for email %', $c$mangaonkaraniket@gmail.com$c$;
  END IF;

  DELETE FROM commonplace_mistakes m USING commonplace_exercises e
   WHERE m.exercise_id = e.id AND e.user_id = uid
     AND e.subject = $c$python$c$ AND e.tags && ARRAY[$c$import:random-module$c$]::text[];
  DELETE FROM commonplace_attempts a USING commonplace_exercises e
   WHERE a.exercise_id = e.id AND e.user_id = uid
     AND e.subject = $c$python$c$ AND e.tags && ARRAY[$c$import:random-module$c$]::text[];
  DELETE FROM commonplace_exercises e
   WHERE e.user_id = uid
     AND e.subject = $c$python$c$ AND e.tags && ARRAY[$c$import:random-module$c$]::text[];

  -- [0] Example 1 — Print a random float between 0 and 1  ->  Random Module  (2 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Example 1 — Print a random float between 0 and 1$c$, NULL, NULL,
          ARRAY[$c$import:random-module$c$, $c$topic:Random Module$c$]::text[], 0)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$# --- Your Attempt ---
# Type your code below:

import random

input = random.random()
print(input)


# --- Correct Output (Do NOT modify) ---
print(example_1_output)









from IPython.display import HTML, display

display(HTML('''
<details>
  <summary><b>Show Answer Code</b></summary>
  <pre>
import random
print(random.random())
  </pre>
</details>
'''))$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$to review$c$, false);
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$%%html
<details>
  <summary><b>Show Answer Code</b></summary>
  <pre>
import random
print(random.random())
  </pre>
</details>$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$to review$c$, false);

  -- [1] Example 2 — Print a random float between 10 and 20  ->  Random Module  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Example 2 — Print a random float between 10 and 20$c$, NULL, NULL,
          ARRAY[$c$import:random-module$c$, $c$topic:Random Module$c$]::text[], 1)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$# --- Your Attempt ---
# Type your code below:

import random

x = random.random(10,20)
print(x)


# --- Correct Output (Do NOT modify) ---
print(example_2_output)




from IPython.display import HTML, display

display(HTML('''
<details>
  <summary><b>Show Answer Code</b></summary>
  <pre>
import random
print(random.uniform(10, 20))
  </pre>
</details>
'''))$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$to review$c$, false);

  -- [2] Example 3 — Print a random integer between 1 and 10  ->  Random Module  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Example 3 — Print a random integer between 1 and 10$c$, NULL, NULL,
          ARRAY[$c$import:random-module$c$, $c$topic:Random Module$c$]::text[], 2)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$# --- Your Attempt ---
# Type your code below:

import random


# --- Correct Output (Do NOT modify) ---
print(example_3_output)




from IPython.display import HTML, display

display(HTML('''
<details>
  <summary><b>Show Answer Code</b></summary>
  <pre>
import random
print(random.randint(1, 10))
  </pre>
</details>
'''))$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$to review$c$, false);

  -- [3] Example 4 — Print a random number from range 1–9  ->  Random Module  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Example 4 — Print a random number from range 1–9$c$, NULL, NULL,
          ARRAY[$c$import:random-module$c$, $c$topic:Random Module$c$]::text[], 3)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$# --- Your Attempt ---
# Type your code below:

import random


# --- Correct Output (Do NOT modify) ---
print(example_4_output)




from IPython.display import HTML, display

display(HTML('''
<details>
  <summary><b>Show Answer Code</b></summary>
  <pre>
import random
print(random.randrange(1, 10))
  </pre>
</details>
'''))$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$to review$c$, false);

  -- [4] Example 5 — Pick a random color from the list  ->  Random Module  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Example 5 — Pick a random color from the list$c$, NULL, NULL,
          ARRAY[$c$import:random-module$c$, $c$topic:Random Module$c$]::text[], 4)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$# --- Your Attempt ---
# Type your code below:

import random
colors = ['red','blue','green','yellow']



# --- Correct Output (Do NOT modify) ---
print(example_5_output)




from IPython.display import HTML, display

display(HTML('''
<details>
  <summary><b>Show Answer Code</b></summary>
  <pre>
import random
colors = ['red','blue','green','yellow']
print(random.choice(colors))
  </pre>
</details>
'''))$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$to review$c$, false);

  -- [5] Example 6 — Pick 2 unique colors from a list  ->  Random Module  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Example 6 — Pick 2 unique colors from a list$c$, NULL, NULL,
          ARRAY[$c$import:random-module$c$, $c$topic:Random Module$c$]::text[], 5)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$# --- Your Attempt ---
# Type your code below:

import random
colors = ['red','blue','green','yellow']


# --- Correct Output (Do NOT modify) ---
print(example_6_output)




from IPython.display import HTML, display

display(HTML('''
<details>
  <summary><b>Show Answer Code</b></summary>
  <pre>
import random
colors = ['red','blue','green','yellow']
print(random.sample(colors, 2))
  </pre>
</details>
'''))$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$to review$c$, false);

  -- [6] Example 7 — Pick 3 colors (repetition allowed)  ->  Random Module  (2 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Example 7 — Pick 3 colors (repetition allowed)$c$, NULL, NULL,
          ARRAY[$c$import:random-module$c$, $c$topic:Random Module$c$]::text[], 6)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$# --- Your Attempt ---
# Type your code below:

import random


# --- Correct Output (Do NOT modify) ---
print(example_7_output)

from IPython.display import HTML, display
display(HTML('''
<details>
  <summary><b>Show Answer Code</b></summary>
  <pre>
import random
colors = ['red','blue','green','yellow']
print(random.choices(colors, k=3))
  </pre>
</details>
'''))$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$to review$c$, false);
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$%%html
<details>
  <summary><b>Show Answer Code</b></summary>
  <pre>
import random
print(random.random())
  </pre>
</details>$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$to review$c$, false);

  -- [7] Example 8 — Shuffle a list of cards  ->  Random Module  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Example 8 — Shuffle a list of cards$c$, NULL, NULL,
          ARRAY[$c$import:random-module$c$, $c$topic:Random Module$c$]::text[], 7)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$# --- Your Attempt ---
# Type your code below:

import random


# --- Correct Output (Do NOT modify) ---
print(example_8_output)




from IPython.display import HTML, display
display(HTML('''
<details>
  <summary><b>Show Answer Code</b></summary>
  <pre>
import random
cards = ['A','K','Q','J','10']
random.shuffle(cards)
print(cards)
  </pre>
</details>
'''))$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$to review$c$, false);

  -- [8] Example 9 — Generate a Gaussian-distributed number  ->  Random Module  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Example 9 — Generate a Gaussian-distributed number$c$, NULL, NULL,
          ARRAY[$c$import:random-module$c$, $c$topic:Random Module$c$]::text[], 8)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$# --- Your Attempt ---
# Type your code below:

import random


# --- Correct Output (Do NOT modify) ---
print(example_9_output)

from IPython.display import HTML, display
display(HTML('''
<details>
  <summary><b>Show Answer Code</b></summary>
  <pre>
import random
print(random.gauss(0, 1))
  </pre>
</details>
'''))$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$to review$c$, false);

  -- [9] Example 19 — Generate a secure hexadecimal token  ->  Random Module  (1 attempt(s))
  INSERT INTO commonplace_exercises (user_id, subject, title, prompt, difficulty, tags, order_index)
  VALUES (uid, $c$python$c$, $c$Example 19 — Generate a secure hexadecimal token$c$, NULL, NULL,
          ARRAY[$c$import:random-module$c$, $c$topic:Random Module$c$]::text[], 9)
  RETURNING id INTO ex_id;
  INSERT INTO commonplace_attempts (user_id, exercise_id, subject, language, code, stdout, passed)
  VALUES (uid, ex_id, $c$python$c$, $c$python$c$, $c$# ===========================
# HIDDEN INTERNAL CODE (Do NOT modify)
# Generates correct outputs for comparison
# ===========================

import random
import string
import secrets

# Example 1
example_1_output = random.random()

# Example 2
example_2_output = random.uniform(10, 20)

# Example 3
example_3_output = random.randint(1, 10)

# Example 4
example_4_output = random.randrange(1, 10)

# Example 5
colors = ['red', 'blue', 'green', 'yellow']
example_5_output = random.choice(colors)

# Example 6
example_6_output = random.sample(colors, 2)

# Example 7
example_7_output = random.choices(colors, k=3)

# Example 8
cards = ['A', 'K', 'Q', 'J', '10']
random.shuffle(cards)
example_8_output = cards

# Example 9
example_9_output = random.gauss(0, 1)

# Example 10
example_10_output = random.expovariate(1.5)

# Example 11
example_11_output = random.betavariate(2, 5)

# Example 12
example_12_output = random.gammavariate(1, 2)

# Example 13
example_13_output = random.triangular(10, 20, 15)

# Example 14
random.seed(42)
example_14_output = random.random()

# Example 15
player = random.randint(1, 6)
computer = random.randint(1, 6)
example_15_output = f"You: {player}, Computer: {computer}"

# Example 16
chars = string.ascii_letters + string.digits + string.punctuation
example_16_output = ''.join(random.choices(chars, k=12))

# Example 17
questions = ["Q1", "Q2", "Q3", "Q4"]
random.shuffle(questions)
example_17_output = questions

# Example 18
data = list(range(1, 101))
example_18_output = random.sample(data, 10)

# Example 19
example_19_output = secrets.token_hex(8)

print("Hidden correct outputs generated. Ready for practice!")$c$,
          NULL, NULL)
  RETURNING id INTO att_id;
  INSERT INTO commonplace_mistakes (user_id, exercise_id, attempt_id, subject, reason, resolved)
  VALUES (uid, ex_id, att_id, $c$python$c$, $c$to review$c$, false);

END
$IMPORT$;

COMMIT;
